# Site Configuration
theme: jekyll-theme-chirpy
baseurl: ""
lang: en
timezone: US/Central

# jekyll-seo-tag settings
title: Mafruha Shifat
tagline: Exploring the Intersection of Technology, Writing, and Rhetoric
description: >- 
  Welcome to my academic corner on the web. As a graduate student specializing in technical writing and rhetoric studies, my passion lies in understanding and unveiling how these domains intersect with technology. 
  Here, you'll find my thoughts, research, and insights. Let's embark on this journey of exploration and learning together.

url: ""
github:
  username: mafruhashifat
twitter:
  username: twitter_username

social:
  name: Mafruha Shifat
  email: example@domain.com
  links:
    - https://twitter.com/mafruhashifat
    - https://github.com/username

google_analytics:
  id: 

# Your own avatar image
avatar: "/assets/img/my_avatar.jpeg"
toc: true

comments:
  active: 

assets:
  self_host:
    enabled: 
    env: 

pwa:
  enabled: true
paginate: 10

# Not recommended to be modified
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
      comments: true 
      toc: true 
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
