baseURL = 'mafruhashifat.github.io'
languageCode = 'en-us'
title = 'Mafruha Shifat'
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Personal Webpage"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support



[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/MafruhaShifat"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4